### ISSUE TITLE
[otelcol-otlp] Building otelcol-otlp breaks in 0.158.0: `vendor/go.opentelemetry.io/collector/confmap/xconfmap/config.go:14:27: undefined: internal.Validator`

### ISSUE THREAD

**Issue by kastl-ars** [open-telemetry/opentelemetry-collector#15727]
### What happened?

**Describe the bug**
Building the otelcol-otlp collector for openSUSE breaks in 0.158.0, while the "core" collector and the ebpf-profiler collector are building fine. Builds in 0.157.0 were working **fine.**

**Steps to reproduce**
Due to the builds being done offline, the first step is running `ocb --skip-compilation=true --config opentelemetry-collector-releases/distributions/otelcol-otlp/manifest.yaml` beforehand and archiving the `_build` directory.

During build, this directory is put into the right place and the compilation is being started.

```
ocb \
        --config distributions/otelcol-otlp/manifest.yaml \
        --skip-generate \
        --skip-get-modules
```

**What did you expect to see?**
Builds in 0.157.0 were working fine.

**What did you see instead?**

```
[   40s] + ocb --config distributions/otelcol-otlp/manifest.yaml --skip-generate --skip-get-modules
[   40s] 2026-08-05T06:23:10.348Z       INFO    internal/command.go:97  OpenTelemetry Collector Builder {"version": "v0.158.0"}
[   40s] 2026-08-05T06:23:10.348Z       INFO    internal/command.go:102 Using config file       {"path": "distributions/otelcol-otlp/manifest.yaml"}
[   40s] 2026-08-05T06:23:10.348Z       INFO    builder/config.go:165   Using go        {"go-executable": "/usr/bin/go"}
[   40s] 2026-08-05T06:23:10.348Z       INFO    builder/main.go:82      Skipping generating source codes.
[   40s] 2026-08-05T06:23:10.348Z       INFO    builder/main.go:176     Generating source codes only, will not update go.mod and retrieve Go modules.
[   40s] 2026-08-05T06:23:10.348Z       INFO    builder/main.go:121     Compiling
[   56s] Error: failed to compile the OpenTelemetry Collector distribution: go subcommand failed with args '[build -trimpath -o otelcol-otlp -ldflags=-s -w -gcflags= -tags grpcnotrace]': exit status 1, error message: # go.opentelemetry.io/collector/confmap/xconfmap
[   56s] vendor/go.opentelemetry.io/collector/confmap/xconfmap/config.go:14:27: undefined: internal.Validator
[   56s] vendor/go.opentelemetry.io/collector/confmap/xconfmap/config.go:21:18: undefined: internal.Validate
[   56s] 
[   56s] error: Bad exit status from /var/tmp/rpm-tmp.UlVQpL (%build)
```

If you need further information, please reach out.

Kind Regards,
Johannes

### Collector version

0.158.0

## Environment
OS: openSUSE Tumbleweed
Compiler: go1.25

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by ucpr** [comment]
I tested this using the same offline build flow in openSUSE Tumbleweed, but could not reproduce the issue.

```text
openSUSE Tumbleweed
go version go1.25.12 linux/arm64
ocb version v0.158.0+dirty
```

Could you try removing the existing `_build` directory and generated `vendor` artifacts, then regenerate everything from a clean state? There may be stale dependencies left over from the previous version.

**Comment by codeboten** [comment]
@kastl-ars can you confirm the version of ocb used in your example?

**Comment by goingforstudying-ctrl** [comment]
This looks like a version skew between `confmap` and `xconfmap` in the generated build graph, not something specific to the openSUSE build setup.

`xconfmap` v0.157.0 still carries the deprecated aliases at `config.go:14`:

```go
type Validator = internal.Validator
```

which reference `confmap/internal/validation.go`. That internal file went away in confmap v1.64.0 when the validation API was stabilized into the public `confmap` package, and the deprecated aliases in `xconfmap` were only removed later, in `xconfmap` v0.158.0 (#15613). So any module graph that resolves `xconfmap` to v0.157.0 while `confmap` is at v1.64.0 or newer fails with exactly this error. Builds at 0.157.0 compiled because both sides were still the v1.63.0/v0.157.0 pair.

Worth checking the `go.mod` in the generated `_build` dir: if `go.opentelemetry.io/collector/confmap/xconfmap` resolves to v0.157.0, bump it to v0.158.0 (explicit `require`/`replace` in the manifest's gomod pins) and regenerate the vendor tree. And since the build is offline from an archived `_build`, make sure the archive was regenerated with the 0.158.0 manifest rather than carried over from 0.157.0.
